DATA_PATH = './data/'
OUTPUT_PATH = './output/'
POINTS_NAME = 'AvailableBinPoints'
INCOMPLETE_POINTS_NAME = 'incompletePoints'
POINTS_PICKED_LIST_NAME = 'pointsPicked'
POINTS_PICKED_MAP_NAME = 'pointsPickedMap'
POPULATION_DATA_NAME = 'population'
